name: Upload Python Package to PyPI when a Release is Created

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/<PYPI_PACKAGE_NAME>
    permissions:
      id-token: write

    steps:
      -  uses: actions/checkout@main

      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://upload.pypi.org/legacy/